/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_funhotel_hmvp_test_jni_JniDemo */

#ifndef _Included_com_funhotel_hmvp_test_jni_JniDemo
#define _Included_com_funhotel_hmvp_test_jni_JniDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_funhotel_hmvp_test_jni_JniDemo
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_funhotel_hmvp_test_jni_JniDemo_getString
  (JNIEnv *, jobject);

/*
 * Class:     com_funhotel_hmvp_test_jni_JniDemo
 * Method:    calendar
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_funhotel_hmvp_test_jni_JniDemo_calendar
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
